"""data/*.json → standalone/data.js 임베드 빌드 스크립트.

빌드 도구 없는 단일 HTML 앱은 file:// 프로토콜에서도 fetch가 막히는 일이
있으므로, JSON 데이터를 JavaScript 모듈로 변환해 직접 import 가능하도록 한다.

사용:  python build_standalone.py
"""
from pathlib import Path
import json

ROOT = Path(__file__).parent
DATA = ROOT / "data"
OUT = ROOT / "standalone" / "data.js"

FILES = ["skills", "questions", "matrix", "scoring_rules", "prescriptions", "guide"]

def main():
    parts = ["// AUTO-GENERATED by build_standalone.py — do not edit by hand.",
             "// Source: data/*.json  (run convert_excel_to_json.py to refresh)\n"]
    for name in FILES:
        path = DATA / f"{name}.json"
        if not path.exists():
            raise FileNotFoundError(f"Missing {path} — run convert_excel_to_json.py first.")
        obj = json.loads(path.read_text(encoding="utf-8"))
        # ensure_ascii=False so Korean stays readable in the bundle
        js = json.dumps(obj, ensure_ascii=False, indent=2)
        parts.append(f"export const {name} = {js};\n")
    OUT.write_text("\n".join(parts), encoding="utf-8")
    size_kb = OUT.stat().st_size / 1024
    print(f"Wrote {OUT}  ({size_kb:.1f} KB)")
    for name in FILES:
        path = DATA / f"{name}.json"
        kb = path.stat().st_size / 1024
        print(f"  - {name:<14s}: {kb:7.1f} KB")

if __name__ == "__main__":
    main()
